### ISSUE TITLE
Cannot compile locally.

### ISSUE THREAD

**Issue by khangaikhuu** [jonathanborenstein/image-gallery#1]
I think jdbc driver dependency in pom.xml not included?
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.tomcat.jdbc.pool.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Cannot load driver class: com.mysql.jdbc.Driver
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 47 more
Caused by: java.lang.IllegalStateException: Cannot load driver class: com.mysql.jdbc.Driver

**Comment by jonathanborenstein** [comment]
If you download the project, and run the `mvn clean package spring-boot:run`  command on the command line it should work. If you import it into an IDE it should work as well. Right now the default is set on a H2 in memory database.

If you want to save the data locally unmark the hash (#) symbols in the application.properties, and put in the information for your database. First you need to make sure MySQL is running on your machine, and then you will need to create a schema to save it to. Just create a basic schema, once the program runs it will create the tables automatically .After that is done, provide the database url, along with the password and username to the application.properties file.

But if you just want to use the program without that, you can download or clone it and it will run on an in memory database right away on localhost:8080.
